baseURL = 'https://raika777.github.io/raw-thoughts/'
theme = 'paper'
title = 'Raw Thoughts'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1
  [languages.fr]
    languageName = 'Fran√ßais'
    contentDir = 'content/fr'
    weight = 2