baseURL = 'https://raika777.github.io/raw-thoughts/'
theme = 'paper'
title = 'Raw Thoughts'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Français"
        url = "/fr/"
        weight = 10

  [languages.fr]
    languageName = 'Français'
    contentDir = 'content/fr'
    weight = 2
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "English"
        url = "/"
        weight = 10